// Command gen-geodata builds the offline geo assets NodeOS ships with:
//
//   web/world.js               simplified world outlines for the peer map
//   internal/geoip/geoip.bin   IP range → country table (gzipped)
//
// Both are generated from public-domain sources and committed, so the
// appliance never contacts a geo-IP service — peer addresses stay on the box.
//
//	go run ./tools/gen-geodata \
//	  -geojson ne_110m_admin_0_countries.geojson \
//	  -rir rir-arin.txt,rir-ripe.txt,rir-apnic.txt,rir-lacnic.txt,rir-afrinic.txt
package main

import (
	"bufio"
	"compress/gzip"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math"
	"net/netip"
	"os"
	"sort"
	"strconv"
	"strings"
)

type geo struct {
	Features []struct {
		Properties map[string]any `json:"properties"`
		Geometry   struct {
			Type        string          `json:"type"`
			Coordinates json.RawMessage `json:"coordinates"`
		} `json:"geometry"`
	} `json:"features"`
}

const (
	mapW = 1000.0
	mapH = 500.0
)

func project(lon, lat float64) (float64, float64) {
	return (lon + 180) / 360 * mapW, (90 - lat) / 180 * mapH
}

func main() {
	geojson := flag.String("geojson", "", "Natural Earth 110m countries GeoJSON")
	rir := flag.String("rir", "", "comma-separated RIR delegated-extended files")
	outWorld := flag.String("out-world", "web/world.js", "world outline output")
	outGeoIP := flag.String("out-geoip", "internal/geoip/geoip.bin", "geoip table output")
	flag.Parse()

	centroids := map[string][2]float64{}
	if *geojson != "" {
		paths := buildWorld(*geojson, centroids)
		writeWorld(*outWorld, paths, centroids)
	}
	if *rir != "" {
		buildGeoIP(strings.Split(*rir, ","), *outGeoIP)
	}
}

// ---------- world outlines ----------

func buildWorld(path string, centroids map[string][2]float64) []string {
	b, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	var g geo
	if err := json.Unmarshal(b, &g); err != nil {
		log.Fatal(err)
	}

	var paths []string
	for _, f := range g.Features {
		iso := propStr(f.Properties, "ISO_A2_EH", "ISO_A2", "iso_a2")
		if iso == "AQ" { // Antarctica: pure noise on a peer map
			continue
		}
		var polys [][][][2]float64
		switch f.Geometry.Type {
		case "Polygon":
			var p [][][2]float64
			if err := json.Unmarshal(f.Geometry.Coordinates, &p); err != nil {
				continue
			}
			polys = append(polys, p)
		case "MultiPolygon":
			if err := json.Unmarshal(f.Geometry.Coordinates, &polys); err != nil {
				continue
			}
		}

		var best [][2]float64
		var bestArea float64
		var sb strings.Builder
		for _, poly := range polys {
			for ri, ring := range poly {
				if ri > 0 {
					continue // skip holes: invisible at this scale
				}
				if a := math.Abs(ringArea(ring)); a > bestArea {
					bestArea, best = a, ring
				}
				if d := ringPath(ring); d != "" {
					sb.WriteString(d)
				}
			}
		}
		if sb.Len() > 0 {
			paths = append(paths, sb.String())
		}
		if iso != "" && iso != "-99" && best != nil {
			lon, lat := ringCentroid(best)
			centroids[iso] = [2]float64{round(lat, 2), round(lon, 2)}
		}
	}
	return paths
}

// ringPath projects a ring and drops points that move less than half a pixel,
// which is where 110m data stops carrying information anyway.
func ringPath(ring [][2]float64) string {
	var sb strings.Builder
	var lastX, lastY float64
	n := 0
	for _, c := range ring {
		x, y := project(c[0], c[1])
		x, y = round(x, 1), round(y, 1)
		if n > 0 && math.Abs(x-lastX) < 0.5 && math.Abs(y-lastY) < 0.5 {
			continue
		}
		if n == 0 {
			fmt.Fprintf(&sb, "M%g %g", x, y)
		} else {
			fmt.Fprintf(&sb, "L%g %g", x, y)
		}
		lastX, lastY = x, y
		n++
	}
	if n < 3 {
		return ""
	}
	sb.WriteString("Z")
	return sb.String()
}

func ringArea(r [][2]float64) float64 {
	var a float64
	for i := 0; i < len(r); i++ {
		j := (i + 1) % len(r)
		a += r[i][0]*r[j][1] - r[j][0]*r[i][1]
	}
	return a / 2
}

func ringCentroid(r [][2]float64) (lon, lat float64) {
	a := ringArea(r)
	if a == 0 {
		for _, c := range r {
			lon += c[0]
			lat += c[1]
		}
		return lon / float64(len(r)), lat / float64(len(r))
	}
	var cx, cy float64
	for i := 0; i < len(r); i++ {
		j := (i + 1) % len(r)
		f := r[i][0]*r[j][1] - r[j][0]*r[i][1]
		cx += (r[i][0] + r[j][0]) * f
		cy += (r[i][1] + r[j][1]) * f
	}
	return cx / (6 * a), cy / (6 * a)
}

func writeWorld(path string, paths []string, centroids map[string][2]float64) {
	var sb strings.Builder
	sb.WriteString("/* Generated by tools/gen-geodata — do not edit.\n")
	sb.WriteString("   Source: Natural Earth 110m admin-0 countries (public domain).\n")
	sb.WriteString("   Equirectangular projection into a 1000×500 viewBox. */\n")
	sb.WriteString("const WORLD_PATHS = [\n")
	for _, p := range paths {
		fmt.Fprintf(&sb, "  %q,\n", p)
	}
	sb.WriteString("];\n\nconst COUNTRY_LATLON = {\n")
	keys := make([]string, 0, len(centroids))
	for k := range centroids {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&sb, "  %q: [%g, %g],\n", k, centroids[k][0], centroids[k][1])
	}
	sb.WriteString("};\n")

	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s: %d outlines, %d centroids, %d KB\n", path, len(paths), len(centroids), sb.Len()/1024)
}

// ---------- geoip table ----------

type v4Range struct {
	start, end uint32
	cc         string
}

type v6Range struct {
	start, end uint64 // high 64 bits of the prefix
	cc         string
}

func buildGeoIP(files []string, out string) {
	var v4 []v4Range
	var v6 []v6Range

	for _, f := range files {
		fh, err := os.Open(strings.TrimSpace(f))
		if err != nil {
			log.Printf("skip %s: %v", f, err)
			continue
		}
		sc := bufio.NewScanner(fh)
		sc.Buffer(make([]byte, 1<<20), 1<<20)
		for sc.Scan() {
			line := sc.Text()
			if line == "" || line[0] == '#' {
				continue
			}
			p := strings.Split(line, "|")
			// registry|cc|type|start|value|date|status|...
			if len(p) < 7 || len(p[1]) != 2 {
				continue
			}
			cc, typ, start, val := p[1], p[2], p[3], p[4]
			if p[6] != "allocated" && p[6] != "assigned" {
				continue
			}
			switch typ {
			case "ipv4":
				addr, err := netip.ParseAddr(start)
				if err != nil || !addr.Is4() {
					continue
				}
				count, err := strconv.ParseUint(val, 10, 32)
				if err != nil || count == 0 {
					continue
				}
				a4 := addr.As4()
				s := binary.BigEndian.Uint32(a4[:])
				v4 = append(v4, v4Range{s, s + uint32(count) - 1, cc})
			case "ipv6":
				addr, err := netip.ParseAddr(start)
				if err != nil || !addr.Is6() {
					continue
				}
				bits, err := strconv.Atoi(val)
				if err != nil || bits <= 0 || bits > 64 {
					continue // deeper than /64: irrelevant for country lookup
				}
				a := addr.As16()
				s := binary.BigEndian.Uint64(a[:8])
				span := uint64(1)<<(64-bits) - 1
				v6 = append(v6, v6Range{s, s + span, cc})
			}
		}
		fh.Close()
	}

	sort.Slice(v4, func(i, j int) bool { return v4[i].start < v4[j].start })
	sort.Slice(v6, func(i, j int) bool { return v6[i].start < v6[j].start })
	v4 = mergeV4(v4)
	v6 = mergeV6(v6)

	// country codes are interned so each range costs 2 bytes for the country
	idx := map[string]uint16{}
	var codes []string
	id := func(cc string) uint16 {
		if v, ok := idx[cc]; ok {
			return v
		}
		v := uint16(len(codes))
		idx[cc] = v
		codes = append(codes, cc)
		return v
	}

	var buf []byte
	appendU32 := func(v uint32) { buf = binary.BigEndian.AppendUint32(buf, v) }
	appendU64 := func(v uint64) { buf = binary.BigEndian.AppendUint64(buf, v) }
	appendU16 := func(v uint16) { buf = binary.BigEndian.AppendUint16(buf, v) }

	// header written after the codes table, so collect payload first
	var v4buf, v6buf []byte
	for _, r := range v4 {
		c := id(r.cc)
		v4buf = binary.BigEndian.AppendUint32(v4buf, r.start)
		v4buf = binary.BigEndian.AppendUint32(v4buf, r.end)
		v4buf = binary.BigEndian.AppendUint16(v4buf, c)
	}
	for _, r := range v6 {
		c := id(r.cc)
		v6buf = binary.BigEndian.AppendUint64(v6buf, r.start)
		v6buf = binary.BigEndian.AppendUint64(v6buf, r.end)
		v6buf = binary.BigEndian.AppendUint16(v6buf, c)
	}

	buf = append(buf, "NGEO1"...)
	appendU16(uint16(len(codes)))
	for _, c := range codes {
		buf = append(buf, c[0], c[1])
	}
	appendU32(uint32(len(v4)))
	appendU32(uint32(len(v6)))
	buf = append(buf, v4buf...)
	buf = append(buf, v6buf...)
	_ = appendU64

	fh, err := os.Create(out)
	if err != nil {
		log.Fatal(err)
	}
	defer fh.Close()
	zw, _ := gzip.NewWriterLevel(fh, gzip.BestCompression)
	if _, err := zw.Write(buf); err != nil {
		log.Fatal(err)
	}
	zw.Close()

	st, _ := fh.Stat()
	fmt.Printf("%s: %d v4 ranges, %d v6 ranges, %d countries, raw %d KB, gz %d KB\n",
		out, len(v4), len(v6), len(codes), len(buf)/1024, st.Size()/1024)
}

// mergeV4 collapses adjacent ranges of the same country — RIR files hand out
// many consecutive blocks, so this roughly halves the table for free.
func mergeV4(in []v4Range) []v4Range {
	if len(in) == 0 {
		return in
	}
	out := in[:1]
	for _, r := range in[1:] {
		last := &out[len(out)-1]
		if r.cc == last.cc && r.start <= last.end+1 {
			if r.end > last.end {
				last.end = r.end
			}
			continue
		}
		out = append(out, r)
	}
	return out
}

func mergeV6(in []v6Range) []v6Range {
	if len(in) == 0 {
		return in
	}
	out := in[:1]
	for _, r := range in[1:] {
		last := &out[len(out)-1]
		if r.cc == last.cc && r.start <= last.end+1 {
			if r.end > last.end {
				last.end = r.end
			}
			continue
		}
		out = append(out, r)
	}
	return out
}

// ---------- helpers ----------

func propStr(m map[string]any, keys ...string) string {
	for _, k := range keys {
		if v, ok := m[k].(string); ok && v != "" && v != "-99" {
			return v
		}
	}
	return ""
}

func round(v float64, dec int) float64 {
	p := math.Pow(10, float64(dec))
	return math.Round(v*p) / p
}
